
import React from 'react';

interface ReportSummaryProps {
  summary: string;
  onReset: () => void;
}

export const ReportSummary: React.FC<ReportSummaryProps> = ({ summary, onReset }) => {
  // A simple markdown-to-html renderer
  const renderMarkdown = (text: string) => {
    let html = text;
    // Bold **text**
    html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
    // Headers ## text
    html = html.replace(/^##\s+(.*$)/gmi, '<h2 class="text-xl font-semibold mt-4 mb-2">$1</h2>');
    // Headers # text
    html = html.replace(/^#\s+(.*$)/gmi, '<h1 class="text-2xl font-bold mb-4">$1</h1>');
    // List items - text or * text
    html = html.replace(/^\s*[-*]\s+(.*$)/gmi, '<li class="ml-6 list-disc">$1</li>');
    // Wrap list items in ul
    html = html.replace(/<li class="ml-6 list-disc">.*/g, (match) => {
      if (!match.startsWith('<ul>')) {
        return '<ul>' + match;
      }
      return match;
    });
    html = html.replace(/(<\/li>)(?!<li class="ml-6 list-disc">)/g, '$1</ul>');
    // Newlines
    html = html.replace(/\n/g, '<br />');

    return { __html: html };
  };

  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-bold text-center text-slate-700 dark:text-slate-100">AI-Generated Report Summary</h2>
      <div className="prose prose-slate dark:prose-invert max-w-none p-4 bg-slate-50 dark:bg-slate-900/50 rounded-lg border border-slate-200 dark:border-slate-700">
        <div dangerouslySetInnerHTML={renderMarkdown(summary)} />
      </div>
      <p className="text-sm text-center text-slate-500 dark:text-slate-400">
        Disclaimer: This summary is generated by an AI based on the information you provided. It is intended for analytical purposes and does not constitute a legal finding.
      </p>
      <div className="text-center">
        <button
          onClick={onReset}
          className="px-6 py-2 bg-red-600 text-white font-semibold rounded-lg hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-opacity-50 transition-colors"
        >
          File Another Report
        </button>
      </div>
    </div>
  );
};
